""""createEachTable"

Revision ID: bfc1f805cdfd
Revises:
Create Date: 2024-02-03 22:01:14.599511+09:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql
from sqlalchemy_utils.types import ChoiceType, PasswordType, URLType

from models import AttainmentType

# revision identifiers, used by Alembic.
revision: str = 'bfc1f805cdfd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lineconfiguration',
    sa.Column('id', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('liff_id_owner', mysql.VARCHAR(length=24), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新日時'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.PrimaryKeyConstraint('id'),
    comment='line構成',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_bin'
    )
    op.create_table('user',
    sa.Column('id', mysql.SMALLINT(unsigned=True), nullable=False),
    sa.Column('lineUserID', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=48), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新日時'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lineUserID'),
    comment='ユーザー',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_bin'
    )
    op.create_table('admin',
    sa.Column('id', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('username', sa.String(length=255, collation='utf8mb4_bin'), nullable=True),
    sa.Column('password', PasswordType(), nullable=True),
    sa.Column('user_id', mysql.SMALLINT(unsigned=True), nullable=True, comment='ユーザー'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新日時'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    comment='管理者',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_bin'
    )
    op.create_table('card',
    sa.Column('id', mysql.SMALLINT(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.SMALLINT(unsigned=True), nullable=False, comment='所有者'),
    sa.Column('attainment', ChoiceType(choices=AttainmentType, impl=mysql.TINYINT()), nullable=False, comment='達成状況'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新日時'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='カード',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_bin'
    )
    op.create_table('rallyconfiguration',
    sa.Column('id', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=48), nullable=True, comment='名前'),
    sa.Column('description', mysql.VARCHAR(length=48), nullable=True, comment='説明'),
    sa.Column('liff_id', mysql.VARCHAR(length=24), nullable=True, comment='スタンプラリー用のliffID'),
    sa.Column('stamp_count', mysql.TINYINT(unsigned=True), nullable=False, comment='スタンプの数'),
    sa.Column('half_complete_count', mysql.TINYINT(unsigned=True), nullable=False, comment='中間達成スタンプの数'),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False, comment='active'),
    sa.Column('card_img', URLType(), nullable=True, comment='スタンプカード用の画像URL'),
    sa.Column('stamp_img', URLType(), nullable=True, comment='スタンプ用の画像URL'),
    sa.Column('half_complete_img', URLType(), nullable=True, comment='中間達成用の画像URL'),
    sa.Column('complete_img', URLType(), nullable=True, comment='達成用の画像URL'),
    sa.Column('line_configuration_id', mysql.TINYINT(unsigned=True), nullable=True, comment='組織'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新日時'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.ForeignKeyConstraint(['line_configuration_id'], ['lineconfiguration.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='スタンプラリーイベント構成',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_bin'
    )
    op.create_table('place',
    sa.Column('id', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False, comment='active'),
    sa.Column('is_base', sa.BOOLEAN(), nullable=False, comment='base'),
    sa.Column('name', mysql.VARCHAR(length=48), nullable=True, comment='店名'),
    sa.Column('altname', mysql.VARCHAR(length=48), nullable=True, comment='表示名'),
    sa.Column('access', mysql.VARCHAR(length=48), nullable=True, comment='住所'),
    sa.Column('gpsLatitude', mysql.DOUBLE(precision=9, scale=6, asdecimal=True), nullable=True, comment='Latitude'),
    sa.Column('gpsLongitude', mysql.DOUBLE(precision=9, scale=6, asdecimal=True), nullable=True, comment='Longtitude'),
    sa.Column('rally_configuration_id', mysql.TINYINT(unsigned=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新日時'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.ForeignKeyConstraint(['rally_configuration_id'], ['rallyconfiguration.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='スタンプの設置場所',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_bin'
    )
    op.create_table('stamp',
    sa.Column('id', mysql.SMALLINT(unsigned=True), nullable=False),
    sa.Column('is_stamped', sa.BOOLEAN(), nullable=False, comment='スタンプが押されているか'),
    sa.Column('card_id', mysql.SMALLINT(unsigned=True), nullable=False, comment='カード'),
    sa.Column('place_id', mysql.TINYINT(unsigned=True), nullable=False, comment='場所'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新日時'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='カード',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_bin'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stamp')
    op.drop_table('place')
    op.drop_table('rallyconfiguration')
    op.drop_table('card')
    op.drop_table('admin')
    op.drop_table('user')
    op.drop_table('lineconfiguration')
    # ### end Alembic commands ###
