""""changeRallyconfigurationColumnHalfComplete9TONone"

Revision ID: ed68b1324349
Revises: bfc1f805cdfd
Create Date: 2024-02-13 04:02:08.419625+09:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql
from sqlalchemy_utils.types import PasswordType

# revision identifiers, used by Alembic.
revision: str = 'ed68b1324349'
down_revision: Union[str, None] = 'bfc1f805cdfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin', 'password',
               existing_type=sa.VARBINARY(length=1024),
               type_=PasswordType(),
               existing_nullable=True)
    op.alter_column('rallyconfiguration', 'half_complete_count',
               existing_type=mysql.TINYINT(unsigned=True),
               nullable=True,
               existing_comment='中間達成スタンプの数')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rallyconfiguration', 'half_complete_count',
               existing_type=mysql.TINYINT(unsigned=True),
               nullable=False,
               existing_comment='中間達成スタンプの数')
    op.alter_column('admin', 'password',
               existing_type=PasswordType(),
               type_=sa.VARBINARY(length=1024),
               existing_nullable=True)
    # ### end Alembic commands ###
