""""addFormUrl"

Revision ID: fe4b844de280
Revises: ed68b1324349
Create Date: 2024-02-23 13:58:48.989659+09:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy_utils.types import URLType

# revision identifiers, used by Alembic.
revision: str = 'fe4b844de280'
down_revision: Union[str, None] = 'ed68b1324349'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rallyconfiguration', sa.Column('form_url', URLType(), nullable=True, comment='アンケートフォーム用URL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rallyconfiguration', 'form_url')
    # ### end Alembic commands ###
