""""addImgToPlace"

Revision ID: 1073746db04b
Revises: fe4b844de280
Create Date: 2024-03-02 15:18:17.605060+09:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy_utils.types import PasswordType, URLType

# revision identifiers, used by Alembic.
revision: str = '1073746db04b'
down_revision: Union[str, None] = 'fe4b844de280'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place', sa.Column('stamp_img', URLType(), nullable=True, comment='スタンプ用の画像URL'))
    # with op.batch_alter_table('place', recreate='never') as batch_op:
    #     batch_op.add_column(
    #         sa.Column('stamp_img', URLType(), nullable=True, comment='スタンプ用の画像URL'),
    #         insert_after="gpsLongitude"
    #     )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('place', 'stamp_img')
    # ### end Alembic commands ###
