""""addscore"

Revision ID: 7796c8ae1c2a
Revises: 1073746db04b
Create Date: 2024-04-01 12:24:07.150196+09:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql
from sqlalchemy_utils.types import PasswordType, UUIDType

# revision identifiers, used by Alembic.
revision: str = '7796c8ae1c2a'
down_revision: Union[str, None] = '1073746db04b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('stamp_ibfk_2', 'stamp', type_='foreignkey')


    op.alter_column('place', 'id',
               existing_type=mysql.TINYINT(unsigned=True),
               type_=UUIDType(),
               existing_nullable=False)
    op.alter_column('stamp', 'place_id',
               existing_type=mysql.TINYINT(unsigned=True),
               type_=UUIDType(),
               existing_comment='場所',
               existing_nullable=False)
    op.add_column('card', sa.Column('score', mysql.SMALLINT(unsigned=True), nullable=True, comment='スコア', default=0))

    # 外部キー制約の追加
    op.create_foreign_key('stamp_ibfk_2', 'stamp', 'place', ['place_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'score')
    op.drop_constraint('stamp_ibfk_2', 'stamp', type_='foreignkey')
    op.alter_column('stamp', 'place_id',
               existing_type=UUIDType(),
               type_=mysql.TINYINT(unsigned=True),
               existing_comment='場所',
               existing_nullable=False)
    op.alter_column('place', 'id',
               existing_type=UUIDType(),
               type_=mysql.TINYINT(unsigned=True),
               existing_nullable=False)
    op.alter_column('admin', 'password',
               existing_type=PasswordType(),
               type_=sa.VARBINARY(length=1024),
               existing_nullable=True)
    op.create_foreign_key('stamp_ibfk_2', 'stamp', 'place', ['place_id'], ['id'])
    # ### end Alembic commands ###
