""""addcardname"

Revision ID: c1093577becc
Revises: 7796c8ae1c2a
Create Date: 2024-04-02 05:25:29.096146+09:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql
from sqlalchemy_utils.types import PasswordType, UUIDType

# revision identifiers, used by Alembic.
revision: str = 'c1093577becc'
down_revision: Union[str, None] = '7796c8ae1c2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('name', mysql.VARCHAR(length=48), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'name')
    # ### end Alembic commands ###
