""""changescoretypesmallint"

Revision ID: f49caa446925
Revises: c1093577becc
Create Date: 2024-04-10 05:27:55.783166+09:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql
from sqlalchemy_utils.types import PasswordType

# revision identifiers, used by Alembic.
revision: str = 'f49caa446925'
down_revision: Union[str, None] = 'c1093577becc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place', sa.Column('score', mysql.SMALLINT(unsigned=True), nullable=False, comment='スコア', default=0))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('place', 'score',
               existing_type=mysql.SMALLINT(unsigned=True),
               type_=mysql.TINYINT(unsigned=True),
               existing_comment='スコア',
               existing_nullable=True)
    # ### end Alembic commands ###
