""""addcardtokenandconstrait"

Revision ID: fb56045a185d
Revises: f49caa446925
Create Date: 2024-05-12 18:12:13.925411+09:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql
from sqlalchemy_utils.types import PasswordType

from models.cardToken import TokenType

# revision identifiers, used by Alembic.
revision: str = 'fb56045a185d'
down_revision: Union[str, None] = 'f49caa446925'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cardtoken',
    sa.Column('id', mysql.SMALLINT(unsigned=True), nullable=False),
    sa.Column('card_id', mysql.SMALLINT(unsigned=True), nullable=False, comment='作成されたカード'),
    sa.Column('token', TokenType(length=32), nullable=False),
    sa.Column('count', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新日時'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    comment='カード',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_bin'
    )
    op.drop_constraint('card_ibfk_1', 'card', type_='foreignkey')
    op.drop_column('card', 'user_id')
    op.create_unique_constraint('card_place_unique', 'stamp', ['card_id', 'place_id'])
    op.add_column('user', sa.Column('card_id', mysql.SMALLINT(unsigned=True), nullable=True, comment='所持カード'))
    op.create_foreign_key(None, 'user', 'card', ['card_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'card_id')
    op.drop_constraint('card_place_unique', 'stamp', type_='unique')
    op.add_column('card', sa.Column('user_id', mysql.SMALLINT(unsigned=True), autoincrement=False, nullable=False, comment='所有者'))
    op.create_foreign_key('card_ibfk_1', 'card', 'user', ['user_id'], ['id'])
    op.drop_table('cardtoken')
    # ### end Alembic commands ###
