""""addgameendtime"

Revision ID: 0a488d99a762
Revises: fb56045a185d
Create Date: 2024-05-16 05:29:47.833831+09:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql
from sqlalchemy_utils.types import PasswordType

# revision identifiers, used by Alembic.
revision: str = '0a488d99a762'
down_revision: Union[str, None] = 'fb56045a185d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('place', 'score',
               existing_type=mysql.SMALLINT(unsigned=True),
               nullable=True,
               existing_comment='スコア')
    op.add_column('rallyconfiguration', sa.Column('end_time', sa.DateTime(), nullable=True, comment='ゲームの終了時刻'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rallyconfiguration', 'end_time')
    op.alter_column('place', 'score',
               existing_type=mysql.SMALLINT(unsigned=True),
               nullable=False,
               existing_comment='スコア')
    # ### end Alembic commands ###
